services:
  fileswift:
    container_name: fileswift
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "5678:5678"

    environment:
      FILESWIFT_DATA_DIR: /data

    volumes:
      - ./data:/data

    restart: unless-stopped